name: Snake animation

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user: '<your_username>'  # replace with your GitHub username
          svg_out: 'output/snake.svg'
          clean: true
